using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Markup;
using Microsoft.UI.Xaml.Media;

namespace Windshot.Shell;

/// <summary>
/// Fluent System Icons, the set Windows 11's own apps use. The path data lives in
/// FluentIcons.g.cs, generated by tools/make-fluent-icons.ps1.
/// </summary>
internal static partial class FluentIcons
{
    /// <param name="filled">The filled style, used for the active tool and on hover.</param>
    public static PathIcon Create(string name, bool filled)
    {
        // A geometry can only belong to one element, so each icon gets a freshly parsed one.
        var data = (Geometry)XamlBindingHelper.ConvertValue(typeof(Geometry), PathData(name, filled));
        return new PathIcon { Data = data };
    }

    /// <summary>An icon's outline on a 20x20 grid, in path markup (e.g. for drawing stickers).</summary>
    public static string PathData(string name, bool filled) => filled ? Paths[name].Filled : Paths[name].Regular;
}
