# Generates src/Windshot/Shell/FluentIcons.g.cs: vector path data for the Fluent System Icons
# Windshot uses (20px designs, regular and filled), extracted from Microsoft's icon fonts.
# The fonts are only needed to run this script; the app ships just the paths.
#
# Usage (Windows PowerShell 5.1, which has WPF's font APIs):
#   powershell -STA -File tools/make-fluent-icons.ps1 [-FontDir <folder>]
# Fonts are downloaded into -FontDir if missing, from github.com/microsoft/fluentui-system-icons (MIT).
param([string]$FontDir = (Join-Path $env:TEMP 'windshot-fluent-icons'))
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName PresentationCore, WindowsBase

# Names as in the Fluent System Icons catalog (ic_fluent_<name>_20_<style>).
$icons = @(
    'save', 'copy', 'arrow_undo', 'arrow_redo',
    'cursor', 'arrow_up_right', 'rectangle_landscape', 'text_t', 'blur',
    'number_circle_1', 'highlight', 'flashlight',
    'grid_dots', 'color_background', 'sparkle', 'pin', 'scan_text'
)

New-Item -ItemType Directory -Force $FontDir | Out-Null
$base = 'https://raw.githubusercontent.com/microsoft/fluentui-system-icons/main/fonts'
foreach ($file in 'FluentSystemIcons-Regular.ttf', 'FluentSystemIcons-Regular.json', 'FluentSystemIcons-Filled.ttf', 'FluentSystemIcons-Filled.json') {
    $path = Join-Path $FontDir $file
    if (-not (Test-Path $path)) { Invoke-WebRequest "$base/$file" -OutFile $path -UseBasicParsing }
}

$em = 20
$culture = [Globalization.CultureInfo]::InvariantCulture
function Get-PathData([string]$name, [string]$style) {
    $face = New-Object Windows.Media.GlyphTypeface (New-Object Uri (Join-Path $FontDir "FluentSystemIcons-$style.ttf"))
    $map = Get-Content (Join-Path $FontDir "FluentSystemIcons-$style.json") -Raw | ConvertFrom-Json
    $key = "ic_fluent_${name}_20_$($style.ToLower())"
    $codepoint = $map.$key
    if ($null -eq $codepoint) { throw "Icon not found: $key" }
    $glyph = $face.GetGlyphOutline($face.CharacterToGlyphMap[[int]$codepoint], $em, $em)
    # Outlines hang from the baseline; shift them into the 0..20 box. Union with itself bakes
    # the shift into the coordinates.
    $shift = New-Object Windows.Media.TranslateTransform 0, ($face.Baseline * $em)
    $geometry = [Windows.Media.Geometry]::Combine($glyph, $glyph, 'Union', $shift)
    $data = $geometry.ToString($culture)
    # Three decimals is far below a device pixel and keeps the file small.
    return [regex]::Replace($data, '-?\d+\.\d+', { param($m) [Math]::Round([double]::Parse($m.Value, $culture), 3).ToString($culture) })
}

$lines = foreach ($name in $icons) {
    $regular = Get-PathData $name 'Regular'
    $filled = Get-PathData $name 'Filled'
    "        [`"$name`"] = (`"$regular`", `"$filled`"),"
}

$out = Join-Path $PSScriptRoot '..\src\Windshot\Shell\FluentIcons.g.cs'
@"
// <auto-generated>
// Generated by tools/make-fluent-icons.ps1 from Fluent System Icons
// (https://github.com/microsoft/fluentui-system-icons, MIT License, Copyright (c) 2020 Microsoft Corporation).
// Do not edit by hand; add icon names to the script and rerun it.
// </auto-generated>

namespace Windshot.Shell;

internal static partial class FluentIcons
{
    /// <summary>Path data for each icon on a 20x20 grid: (regular, filled).</summary>
    private static readonly Dictionary<string, (string Regular, string Filled)> Paths = new()
    {
$($lines -join "`r`n")
    };
}
"@ | Set-Content -Path $out -Encoding utf8
"Wrote $out ($($icons.Count) icons, $((Get-Item $out).Length) bytes)"
